# ============================================================
# 18. DETERMINE POST-CHECK STATUS
# ============================================================

- name: OS Update | Determine post-check status
  ansible.builtin.set_fact:
    os_update_postcheck_status: >-
      {% if
        (os_update_postcheck_kernel.rc | default(1) | int) == 0
        and
        (
          ansible_os_family != 'Debian'
          or
          (os_update_postcheck_dpkg.rc | default(1) | int) == 0
        )
        and
        (
          ansible_os_family != 'RedHat'
          or
          (os_update_postcheck_rpm.rc | default(1) | int) == 0
        )
        and
        (
          ansible_os_family != 'Suse'
          or
          (os_update_postcheck_zypper.rc | default(1) | int) == 0
        )
      %}
      SUCCESS
      {% else %}
      FAILED
      {% endif %}
