---

- name: Debian/Ubuntu patch
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"
  register: upgrade_result

- name: RHEL/CentOS/Rocky/Alma patch
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
  register: upgrade_result

- name: SUSE patch
  ansible.builtin.zypper:
    name: "*"
    state: latest
  when: ansible_os_family == "Suse"
  register: upgrade_result
