- name: Perform Maintenance Tasks
  hosts: "{{ hosts.split(';') | join(':') }}"
  gather_facts: true

  vars:
    EXCLUDE_PKGS: "{{ lookup('env', 'EXCLUDE_PKGS') | default('') }}"
    exclude_packages_list: >-
      {{ EXCLUDE_PKGS.split(';')
         | map('trim')
         | reject('equalto', '')
         | list }}

  roles:
    - os-tasks
