---
    - name: Remove disabled snaps
      ansible.builtin.shell:
        cmd: "snap list --all"
      register: snap_list_output
      changed_when: false

    - name: Process snap list output and remove disabled snaps
      ansible.builtin.shell:
        cmd: "snap remove {{ item.0 }} --revision={{ item.1 }}"
      with_items: "{{ snap_list_output.stdout_lines }}"
      when: "'disabled' in item"
      changed_when: false

    - name: Vacuum journalctl logs to limit size to 20M
      ansible.builtin.shell:
        cmd: "journalctl --vacuum-size=20M"
      changed_when: false

    - name: Fix Broken packages
      ansible.builtin.shell:
        cmd: "DEBIAN_FRONTEND=noninteractive dpkg --configure -a"
      changed_when: false
      
    - name: Perform apt update to check for updates
      ansible.builtin.shell:
        cmd: "apt update"
      changed_when: false

    - name: Check kernel version before patching
      ansible.builtin.command:
        cmd: "uname -r"
      register: kernel_version_before
      changed_when: false

    - name: Hold specified packages
      ansible.builtin.shell:
        cmd: "apt-mark hold {{ item }}"
      with_items: "{{ EXCLUDE_PKGS.split(';') }}"
      when: EXCLUDE_PKGS is defined and EXCLUDE_PKGS | length > 0
      ignore_errors: true
      changed_when: false

    - name: Perform OS patch update
      ansible.builtin.shell:
        cmd: "DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y"
      register: apt_upgrade_simulate
      changed_when: false


    - name: Get current kernel version
      command: uname -r
      register: kernel_version_before

    - name: Get the latest installed kernel version from dpkg.log
      shell: |
        grep 'install linux-image' /var/log/dpkg.log | tail -n 1 | awk '{print $4}' | cut -d ":" -f1 | cut -d "-" -f3-
      register: latest_kernel_install
      changed_when: false

    - name: Debug extracted latest kernel version
      debug:
        msg: "Latest installed kernel version: {{ latest_kernel_install.stdout }}"

    - name: Check if a new kernel was installed
      set_fact:
        reboot_required: "{{ latest_kernel_install.stdout.strip() != kernel_version_before.stdout.strip() }}"

    - name: Debug information about kernel versions
      debug:
        msg:
          - "Current kernel version: {{ kernel_version_before.stdout.strip() }}"
          - "New kernel version detected: {{ latest_kernel_install.stdout.strip() }}"
          - "Reboot required: {{ reboot_required }}"

    - name: Reboot if a new kernel is installed
      ansible.builtin.reboot:
      when: reboot_required
      ignore_errors: true
      changed_when: true
