- name: Aggregate results safely
  set_fact:
    user_search_results: "{{ user_search_results + [result_item] }}"
  vars:
    stdout_val: "{{ item.stdout | default('') }}"
    match_type_match: >-
      {{
        (stdout_val | regex_search('match_type=([^|]+)', '\\1'))[0]
        if (stdout_val | regex_search('match_type=([^|]+)', '\\1')) is not none else 'none'
      }}
    username_match: >-
      {{
        (stdout_val | regex_search('user=([^|]+)', '\\1'))[0]
        if (stdout_val | regex_search('user=([^|]+)', '\\1')) is not none else ''
      }}
    gecos_match: >-
      {{
        (stdout_val | regex_search('gecos=(.*)', '\\1'))[0]
        if (stdout_val | regex_search('gecos=(.*)', '\\1')) is not none else ''
      }}
    result_item: >-
      {{
        {
          'host': inventory_hostname,
          'input': item.item,
          'match_type': match_type_match,
          'username': username_match,
          'gecos': gecos_match
        }
      }}
  loop: "{{ user_info.results }}"
  loop_control:
    loop_var: item
