---
- name: Check Local User
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: false

  vars:
    #target_username: "{{ lookup('env', 'TARGET_USERNAME') }}"
    target_usernames_list: "{{ lookup('env', 'TARGET_USERNAME').split(';') }}"
    
  tasks:
    - name: Display local user
      command: "id {{ target_username }}"
      register: user_info
      ignore_errors: true

    - debug:
        msg: "User '{{ target_username }}' exists on {{ inventory_hostname }}"
      delegate_to: all
      when: user_info.rc == 0
