---
- name: Check if user exists
  hosts: all  # Define the target hosts here or use a specific group

  tasks:
    - name: Check if the user exists
      #become: true  # If needed, run this task with sudo
      #become_user: root  # If needed, run this task as a specific user
      user:
        name: "{{ USERNAME }}"  # Username to check
      register: user_exists

    - name: Print the result
      debug:
        msg: "User '{{ USERNAME }}' {{ 'exists' if user_exists|bool else 'does not exist' }}"
