---
- name: Find Local Users
  hosts: all
  tasks:
    - name: Gather local user information
      shell: getent passwd | grep -v '/bin/false' | grep -v '/sbin/nologin' | cut -d: -f1"
      register: local_users_info

    - name: Extract local users
      set_fact:
        local_users: "{{ local_users_info.stdout_lines | map('split', ':') | map(attribute=0) | list }}"
      
    - name: Display local users
      debug:
        var: local_users
