---
- name: Check Local Users
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: false

  vars:
    # Splitting TARGET_USERNAME into a list of usernames
    target_usernames_list: "{{ lookup('env', 'TARGET_USERNAME').split(';') }}"
  
  tasks:
    # Loop through each username in the list
    - name: Check existence of multiple users
      shell: "id {{ item }}"
      register: user_info
      ignore_errors: true
      loop: "{{ target_usernames_list }}"
      loop_control:
        loop_var: item

    # Debug message for each user existence
    - name: Display user existence
      debug:
        msg: "User '{{ item.item }}' exists on {{ inventory_hostname }}"
      loop: "{{ user_info.results }}"
      when: item.stdout != ""  # Check if there is stdout to determine existence

    # Debug message for each user non-existence
    - name: Display user does not exist
      debug:
        msg: "User '{{ item.item }}' does not exist on {{ inventory_hostname }}"
      loop: "{{ user_info.results }}"
      when: item.stdout == ""  # Check if stdout is empty to determine non-existence
