---
- name: Check Local User
  hosts: "{{ server_name }}"
  gather_facts: false

  vars:
    user_name: "{{ lookup('env', 'USER_NAME') }}"

  tasks:
    - name: Display local user
      command: "id {{ user_name }}"
      register: user_info
      ignore_errors: true

    - debug:
        msg: "User '{{ user_name }}' exists on {{ inventory_hostname }}"
      when: user_info.rc == 0

    - debug:
        msg: "User '{{ user_name }}' does not exist on {{ inventory_hostname }}"
      when: user_info.rc != 0
