---
- name: Check for user
  hosts: all
  tasks:
    - name: Check if user exists
      command: id "{{ USERNAME }}"
      register: user_check
      ignore_errors: yes

    - name: Print result
      debug:
        msg: "User {{ USERNAME }} exists: {{ user_check.rc == 0 }}"
