---
- name: Check User
  hosts: localhost
  tasks:
    - name: Check if user exists
      command: "id {{ username }}"
      register: user_check
      ignore_errors: yes

    - name: Display result
      debug:
        msg: "{{ 'User exists' if user_check.rc == 0 else 'User does not exist' }}"
