---
- name: Check Local User
  hosts: "{{ server_name }}"
  gather_facts: false

  vars:
    target_username: "{{ lookup('env', 'TARGET_USERNAME') }}"

  tasks:
    - name: Display local user
      command: "id {{ target_username }}"
      register: user_info
      ignore_errors: true

    - debug:
        msg: "User '{{ target_username }}' exists on {{ INVENTORY_HOSTNAME }}"
      delegate_to: all
      when: user_info.rc == 0
