---
- name: Check Local Users
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: false

  vars:
    # Splitting TARGET_USERNAME into a list of usernames
    target_usernames_list: "{{ lookup('env', 'TARGET_USERNAME').split(';') }}"
    user_existence_results: []  # Initialize an empty list to store results

    # Define colors for existence and non-existence
    color_exists: '\033[0;32m'  # Green color
    color_not_exists: '\033[0;31m'  # Red color
    color_reset: '\033[0m'  # Reset to default color

  tasks:
    # Loop through each username in the list
    - name: Check existence of multiple users
      shell: "id {{ item }}"
      register: user_info
      ignore_errors: true
      loop: "{{ target_usernames_list }}"
      loop_control:
        loop_var: item

    # Aggregate results into a list
    - set_fact:
        user_existence_results: "{{ user_existence_results + [{'host': inventory_hostname, 'username': item.item, 'exists': item.rc == 0}] }}"
      loop: "{{ user_info.results }}"
      loop_control:
        loop_var: item

    # Final message per host
    - name: Final message per host
      debug:
        msg: >
          "User {{ color_exists if result.exists else color_not_exists }}{{ 'exists' if result.exists else 'does not exist' }}{{ color_reset }} on {{ inventory_hostname }}"
      loop: "{{ user_existence_results }}"
      loop_control:
        loop_var: result
