---
- name: Check Local User
  hosts: "masters"
  gather_facts: false

  vars:
    target_username: "{{ lookup('env', 'TARGET_USERNAME') }}"

  tasks:
    - name: Display local user
      command: "id {{ target_username }}"
      register: user_info
      ignore_errors: true

    - debug:
        msg: "User '{{ target_username }}' does not exist on {{ inventory_hostname }}"
      delegate_to: all
      when: user_info.rc != 0
