---
- name: Check Local User
  hosts: all
  gather_facts: false

  vars:
    target_username: "{{ lookup('env', 'TARGET_USERNAME') }}"
    target_servername: "{{ lookup('env', 'SERVER_NAME') }}"

  tasks:
    - name: Display local user
      command: "id {{ target_username }}"
      register: user_info
      ignore_errors: true

    - debug:
        msg: "User '{{ target_username }}' exists on {{ target_servername }}"
      delegate_to: all
      when: user_info.rc == 0

    - debug:
        msg: "User '{{ target_username }}' doe not exist on {{ target_servername }}"
      delegate_to: all
      when: user_info.rc != 0
