---
- name: Check Local User
  hosts: all
  gather_facts: false

  vars:
    target_username: "{{ lookup('env', 'TARGET_USERNAME') }}"
  vars:
    server_name: "{{ lookup('env', 'SERVER_NAME') }}"
  
  tasks:
    - name: Display local user
      command: "id {{ target_username }}"
      register: user_info
      ignore_errors: true

    - debug:
        msg: "User '{{ target_username }}' exists on {{ server_hostname }}"
      when: user_info.rc == 0
