---
- name: Check if a local user exists on inventory hosts
  #hosts: "{{ hosts.split(';') }}"
  hosts: all
  gather_facts: false

  vars:
    target_username: "{{ lookup('env', 'TARGET_USERNAME') }}"

  tasks:
    - name: Check if user exists
      ansible.builtin.command: "id {{ target_username }}"
      register: user_info
      ignore_errors: true

    - name: Print where user exists
      ansible.builtin.debug:
        msg: "User '{{ target_username }}' exists on {{ inventory_hostname }}"
      when: user_info.rc == 0
