---
- name: Check Users on Servers
  hosts: "{{ target_servers }}"
  tasks:
    - name: Display users
      command: "cat /etc/passwd"
      register: users_output
      changed_when: false
      ignore_errors: yes

    - debug:
        msg: "{{ users_output.stdout_lines }}"
