---
- name: Check Users by Username or GECOS Field
  hosts: "{{ hosts.split(';') }}"
  gather_facts: false

  vars:
    input_identifiers: "{{ lookup('env', 'TARGET_USERNAME').split(';') }}"
    user_search_results: []

  tasks:
    - name: Check for user existence by username or GECOS
      shell: |
        input="{{ item }}"
        # Try to find by username (id)
        if id "$input" >/dev/null 2>&1; then
          gecos=$(getent passwd "$input" | cut -d ':' -f 5)
          echo "match_type=username|user=$input|gecos=$gecos"
        else
          # Try to find by GECOS (full name)
          match=$(getent passwd | awk -F: -v name="$input" '$5 ~ name {print $1 ":" $5}' | head -n 1)
          if [ -n "$match" ]; then
            user=$(echo "$match" | cut -d ':' -f 1)
            gecos=$(echo "$match" | cut -d ':' -f 2)
            echo "match_type=gecos|user=$user|gecos=$gecos"
          else
            echo "match_type=none|user=|gecos="
          fi
        fi
      register: user_info
      ignore_errors: true
      loop: "{{ input_identifiers }}"
      loop_control:
        loop_var: item

    - name: Aggregate results
      set_fact:
        user_search_results: "{{ user_search_results + [{
          'host': inventory_hostname,
          'input': item.item,
          'match_type': (item.stdout | reg_
