---
- name: Find Local Users
  hosts: all
  tasks:
    - name: Gather local user information
      ansible.builtin.shell: getent passwd
      register: local_users_info

    - name: Extract local users
      set_fact:
        local_users: "{{ local_users_info.stdout_lines | map('split', ':') | map(attribute=0) | list }}"
      
    - name: Display local users
      debug:
        var: local_users
