---
- name: Gather installed packages from working host
  hosts: "{{ working_host }}"
  gather_facts: false
  tasks:
    - name: Run dpkg to get installed packages
      shell: dpkg --get-selections | grep -w install
      register: package_list

    - name: Save package list to a file
      copy:
        content: "{{ package_list.stdout }}"
        dest: "/tmp/packages_{{ inventory_hostname }}.txt"

- name: Gather installed packages from nonworking host
  hosts: "{{ nonworking_host }}"
  gather_facts: false
  tasks:
    - name: Run dpkg to get installed packages
      shell: dpkg --get-selections | grep -w install
      register: package_list

    - name: Save package list to a file
      copy:
        content: "{{ package_list.stdout }}"
        dest: "/tmp/packages_{{ inventory_hostname }}.txt"

- name: Fetch package lists to control node
  hosts: "{{ working_host }},{{ nonworking_host }}"
  gather_facts: false
  tasks:
    - name: Fetch the package list file
      fetch:
        src: "/tmp/packages_{{ inventory_hostname }}.txt"
        dest: "./fetched/"
        flat: true

- name: Compare packages locally
  hosts: localhost
  gather_facts: false
  vars:
    working_file: "fetched/packages_{{ working_host }}.txt"
    nonworking_file: "fetched/packages_{{ nonworking_host }}.txt"
    compare_script_url: "https://raw.githubusercontent.com/tejaspandhare/python/main/scripts/compare_packages.py"
  tasks:
    - name: Download comparison script from GitHub
      get_url:
        url: "{{ compare_script_url }}"
        dest: "{{ playbook_dir }}/compare_packages.py"
        mode: '0755'

    - name: Run comparison script
      command: >
        python3 compare_packages.py {{ working_file }} {{ nonworking_file }}
      args:
        chdir: "{{ playbook_dir }}"
      register: compare_result
      failed_when: false  # You control failure based on output if needed

    - name: Show clean comparison output
      debug:
        msg: "{{ compare_result.stdout }}"
