- name: Compare packages between working and nonworking host
  command: >
    python3 compare_packages.py {{ working_file }} {{ nonworking_file }}
  args:
    chdir: "{{ playbook_dir }}"
  register: compare_result
  failed_when: compare_result.rc != 0

- name: Show comparison output line by line
  debug:
    msg: "{{ item }}"
  loop: "{{ compare_result.stdout_lines }}"
