---
- name: Gather Linux system details
  hosts: "{{ hosts.split(';') }}"
  gather_facts: true
  become: true

  tasks:
    - name: Get CPU information
      command: lscpu
      register: cpu_info
      changed_when: false

    - name: Get Memory information
      command: free -h
      register: memory_info
      changed_when: false

    - name: Get serial number
      command: dmidecode -s system-serial-number
      register: serial_number
      changed_when: false
      failed_when: false

    - name: Get system manufacturer to check machine type (VMware, Xen, or physical)
      command: dmidecode -s system-manufacturer
      register: manufacturer
      changed_when: false
      failed_when: false

    - name: Output CPU information
      debug:
        var: cpu_info.stdout

    - name: Output Memory information
      debug:
        var: memory_info.stdout

    - name: Output Serial Number
      debug:
        var: serial_number.stdout

    - name: Output Manufacturer
      debug:
        var: manufacturer.stdout
