---
- name: Perform Maintenance Tasks
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: true  # Ensure facts are gathered to check OS version

  tasks:
    - name: Get distribution name
      command: cat /etc/os-release
      register: distro_info

    - name: Get CPU information
      command: lscpu
      register: cpu_info

    - name: Get RAM information
      command: free -h
      register: ram_info

    - name: Get kernel version
      command: uname -r
      register: kernel_version

    - name: Get hardware type
      command: sudo dmidecode -s system-product-name
      register: hardware_type
      become: true  # Use become to run as root for dmidecode

    - name: Aggregate information
      set_fact:
        system_info:
          hostname: "{{ inventory_hostname }}"
          distribution: "{{ distro_info.stdout | replace('\n', ' ') }}"
          cpu: "{{ cpu_info.stdout | replace('\n', ' ') }}"
          ram: "{{ ram_info.stdout | replace('\n', ' ') }}"
          kernel: "{{ kernel_version.stdout }}"
          hardware: "{{ hardware_type.stdout | replace('\n', ' ') }}"

    - name: Collect all system information for CSV
      set_fact:
        all_systems_info: "{{ all_systems_info | default([]) + [system_info] }}"

    - name: Create CSV file header
      lineinfile:
        path: "{{ lookup('env', 'WORKSPACE') }}/system_info.csv"
        line: "Hostname,Distribution,CPU,RAM,Kernel,Hardware"
        state: present
        create: yes

    - name: Append system information to CSV
      lineinfile:
        path: "{{ lookup('env', 'WORKSPACE') }}/system_info.csv"
        line: "{{ item.hostname }},{{ item.distribution }},{{ item.cpu }},{{ item.ram }},{{ item.kernel }},{{ item.hardware }}"
      loop: "{{ all_systems_info | sort(attribute='hostname') }}"

    - name: Display path to CSV file
      debug:
        msg: "CSV file created at {{ lookup('env', 'WORKSPACE') }}/system_info.csv"
