---
- name: Perform Maintenance Tasks
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: true  # Ensure facts are gathered to check OS version

  tasks:
    - name: Get distribution name
      command: cat /etc/os-release
      register: distro_info

    - name: Get CPU information
      command: lscpu
      register: cpu_info

    - name: Get RAM information
      command: free -h
      register: ram_info

    - name: Get kernel version
      command: uname -r
      register: kernel_version

    - name: Get hardware type
      command: sudo dmidecode -s system-product-name
      register: hardware_type
      become: true  # Use become to run as root for dmidecode

    - name: Display gathered information
      debug:
        msg: |
          **System Information for {{ inventory_hostname }}**
          - **Distribution**: 
            {{ distro_info.stdout | replace('\n', ', ') }}
          - **CPU**: 
            {{ cpu_info.stdout | replace('\n', ', ') }}
          - **RAM**: 
            {{ ram_info.stdout | replace('\n', ', ') }}
          - **Kernel Version**: 
            {{ kernel_version.stdout }}
          - **Hardware Type**: 
            {{ hardware_type.stdout }}
