---
- name: Perform Maintenance Tasks
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: true  # Ensure facts are gathered to check OS version

  tasks:
    - name: Get distribution name
      command: cat /etc/os-release
      register: distro_info

    - name: Get CPU information
      command: lscpu
      register: cpu_info

    - name: Get RAM information
      command: free -h
      register: ram_info

    - name: Get kernel version
      command: uname -r
      register: kernel_version

    - name: Get hardware type
      command: sudo dmidecode -s system-product-name
      register: hardware_type
      become: true  # Use become to run as root for dmidecode

    - name: Aggregate information
      set_fact:
        system_info:
          hostname: "{{ inventory_hostname }}"
          distribution: "{{ distro_info.stdout }}"
          cpu: "{{ cpu_info.stdout }}"
          ram: "{{ ram_info.stdout }}"
          kernel: "{{ kernel_version.stdout }}"
          hardware: "{{ hardware_type.stdout }}"

    - name: Gather all system information
      group_by:
        key: "all_systems"

    - name: Sort and display gathered information
      debug:
        msg: |
          ### System Information for **{{ item.hostname }}** ###
          | **Field**           | **Value**                                     |
          |---------------------|-----------------------------------------------|
          | Distribution        | {{ item.distribution | regex_replace('^', '  ') | regex_replace('\\n', '\\n  ') }} |
          | CPU                 | {{ item.cpu | regex_replace('^', '  ') | regex_replace('\\n', '\\n  ') }}         |
          | RAM                 | {{ item.ram | regex_replace('^', '  ') | regex_replace('\\n', '\\n  ') }}         |
          | Kernel Version      | {{ item.kernel }}                             |
          | Hardware Type       | {{ item.hardware }}                           |
          |---------------------|-----------------------------------------------|
      loop: "{{ groups['all_systems'] | map('extract', hostvars) | sort(attribute='hostname') }}"
