---
- name: Install packages on multiple servers (multi-platform)
  hosts: "{{ hosts.split(';') }}"
  gather_facts: true
  become: true

  vars:
    pkg_list_raw: "{{ pkg_list | default('') }}"
    packages_list: "{{ pkg_list_raw.split(';') | map('trim') | list }}"

  tasks:
    - name: Debug list of packages to install
      debug:
        msg: "Packages to install: {{ packages_list }}"

    - name: Install packages on Ubuntu/Debian
      ansible.builtin.apt:
        name: "{{ packages_list }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install packages on RHEL/CentOS
      ansible.builtin.yum:
        name: "{{ packages_list }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install packages on SUSE
      ansible.builtin.zypper:
        name: "{{ packages_list }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Suse"

    - name: Clean up APT cache (Debian)
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Clean up YUM cache (RedHat)
      ansible.builtin.yum:
        name: "*"
        state: latest
        autoremove: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Clean up Zypper cache (SUSE)
      ansible.builtin.shell: "zypper clean --all"
      when: ansible_facts['os_family'] == "Suse"
      changed_when: false
