---
- name: Check home directories for modification
  hosts: "{{ hosts.split(';') }}"
  gather_facts: true

  tasks:
    - name: Get list of home directories
      find:
        paths: /home
        file_type: directory
      register: home_dirs

    - name: Check last modified time of home directories
      stat:
        path: "{{ item.path }}"
      register: dir_stat
      loop: "{{ home_dirs.files }}"

    - name: Print directories not modified in the last 10 days
      debug:
        msg: "{{ item.item.path }} last modified date: {{ (item.stat.mtime | to_datetime) | strftime('%Y-%m-%d') }}"
      when: (ansible_date_time.epoch | int - item.stat.mtime) > (10 * 86400)
      loop: "{{ dir_stat.results }}"
      loop_control:
        label: "{{ item.item.path }}"


