---
- name: Create user with UID, GID, comment, home directory, and SSH key
  hosts: all
  become: true

  vars:
    server_name: ""
    user_id: ""
    user_gid: ""
    gcos_comment: ""
    public_key: ""
    home_directory: ""

  tasks:

    - name: Show target server info
      debug:
        msg: "Target server: {{ server_name }}, Creating user: {{ user_id }}, Home: {{ home_directory }}"

    - name: Ensure group exists (if GID is provided)
      group:
        name: "{{ user_id }}"
        gid: "{{ user_gid | default(omit) }}"
        state: present
      when: user_gid != ""

    - name: Ensure user exists with custom home, UID, GID, comment
      user:
        name: "{{ user_id }}"
        uid: "{{ user_id | int if user_id != '' else omit }}"
        group: "{{ user_id if user_gid != '' else omit }}"
        comment: "{{ gcos_comment }}"
        home: "{{ home_directory }}"
        shell: /bin/bash
        create_home: true

    - name: Set authorized SSH key for the user
      authorized_key:
        user: "{{ user_id }}"
        key: "{{ public_key }}"
        state: present
        path: "{{ home_directory }}/.ssh/authorized_keys"
