---
- name: Check subdirectories for modification
  hosts: "{{ hosts.split(';') }}"
  gather_facts: true

  tasks:
    - name: Get list of home directories
      find:
        paths: /home
        file_type: directory
      register: home_dirs

    - name: Check last modified time of subdirectories
      stat:
        path: "{{ item.path }}"
      register: dir_stat
      loop: "{{ home_dirs.files }}"

    - name: List subdirectories not modified in the last 10 days
      debug:
        msg: "Subdirectory {{ item.item.path }} last modified date: {{ item.stat.mtime | int | to_datetime('%Y-%m-%d') }}"
      when: (ansible_date_time.epoch | int - item.stat.mtime) > (10 * 86400)
      loop: "{{ dir_stat.results }}"
      loop_control:
        label: "{{ item.item.path }}"
