vars:
  pkg_list_raw: "{{ pkg_list | default('') }}"
  pkg_list: "{{ pkg_list_raw.split(';') | map('trim') | list }}"

tasks:
  - name: Debug list of packages to install/upgrade
    debug:
      msg: "Packages to install/upgrade: {{ pkg_list }}"

  - name: Install or upgrade packages on Ubuntu/Debian
    ansible.builtin.apt:
      name: "{{ pkg_list }}"
      state: absent
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Install or upgrade packages on RHEL/CentOS
    ansible.builtin.yum:
      name: "{{ pkg_list }}"
      state: absent
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install or upgrade packages on SUSE
    ansible.builtin.zypper:
      name: "{{ pkg_list }}"
      state: absent
      update_cache: yes
    when: ansible_facts['os_family'] == "Suse"
