---
- name: Remove a package from multiple Linux distros
  hosts: "{{ hosts.split(';') }}" 
  gather_facts: true 
  become: yes
  vars:
    pkg_list_raw: "{{ pkg_list | default('') }}"
     pkg_list: "{{ pkg_list_raw.split(';') | map('trim') | list }}"

  tasks:

    - name: Remove package on Ubuntu/Debian
      apt:
        name: "{{ package_name }}"
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove package on RHEL/CentOS/Fedora
      yum:
        name: "{{ package_name }}"
        state: absent
      when: ansible_facts['os_family'] == "RedHat"

    - name: Remove package on SUSE
      zypper:
        name: "{{ package_name }}"
        state: absent
      when: ansible_facts['os_family'] == "Suse"
