---
- name: Perform SSH fix Tasks
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: true  # Ensure facts are gathered to check OS version

  tasks:
    - name: Upgrade SSH on Ubuntu/Debian
      apt:
        name: openssh-server
        state: latest
        update_cache: yes
        dpkg_options: 'force-confdef,force-confold'
      register: ssh_update
      when: ansible_os_family == "Debian"

    - name: Restart SSH on Ubuntu/Debian
      service:
        name: ssh
        state: restarted
      when: ssh_update.changed and ansible_os_family == "Debian"

    - name: Modify sshd config redhat
      lineinfile:
        path: /etc/ssh/sshd_config
        state:  present
        regexp: "^LoginGraceTime"
        insertafter: "^#LoginGraceTime"
        line: "LoginGraceTime 0"
        validate: "/usr/sbin/sshd -tf %s"
        backup: true
      when: ansible_os_family == "RedHat"

    - name: Restart SSH on RedHat
      service:
        name: sshd
        state: restarted
      when: ansible_os_family == "RedHat"
