---
- name: Perform Maintenance Tasks
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: true  # Ensure facts are gathered to check OS version

  tasks:
    - name: Remove disabled snaps
      ansible.builtin.shell:
        cmd: "snap list --all"
      register: snap_list_output
      changed_when: false

    - name: Process snap list output and remove disabled snaps
      ansible.builtin.shell:
        cmd: "snap remove {{ item.0 }} --revision={{ item.1 }}"
      with_items: "{{ snap_list_output.stdout_lines }}"
      when: "'disabled' in item"
      changed_when: false

    - name: Vacuum journalctl logs to limit size to 20M
      ansible.builtin.shell:
        cmd: "journalctl --vacuum-size=20M"
      changed_when: false

    - name: Perform apt update to check for updates
      ansible.builtin.shell:
        cmd: "apt update && dpkg  --configure -a"
      changed_when: false

    - name: Check kernel version before patching
      ansible.builtin.command:
        cmd: "uname -r"
      register: kernel_version_before
      changed_when: false

    - name: Check for package upgrades without performing them
      ansible.builtin.shell:
        cmd: "apt-get --simulate dist-upgrade"
      register: apt_upgrade_simulate
      changed_when: false

    - name: Perform apt-get dist-upgrade if upgrades are detected
      ansible.builtin.shell:
        cmd: "DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y"
      register: apt_upgrade_result
      changed_when: "'0 upgraded, 0 newly installed' not in apt_upgrade_result.stdout"
      when: apt_upgrade_simulate.stdout_lines | length > 0

    - name: Restart Docker service if upgraded and prompt appears
      ansible.builtin.command:
        cmd: "DEBIAN_FRONTEND=noninteractive apt-get install -y --reinstall docker.io"
      register: docker_restart_result
      changed_when: "'Automatically restart Docker daemon?' in docker_restart_result.stdout"

    - name: Check kernel version after patching
      ansible.builtin.command:
        cmd: "uname -r"
      register: kernel_version_after
      changed_when: false

    - name: Display OS version changes
      ansible.builtin.debug:
        msg: |
          OS version changes:
            - Before patching: {{ kernel_version_before.stdout }}
            - After patching : {{ kernel_version_after.stdout }}
