---
- name: Perform Maintenance Tasks
  hosts: "{{ hosts.split(';') }}"  # Split SERVER_NAME into a list
  gather_facts: true  # Ensure facts are gathered to check OS version

  tasks:
    - name: Remove disabled snaps
      ansible.builtin.shell:
        cmd: "snap list --all"
      register: snap_list_output
      changed_when: false

    - name: Process snap list output and remove disabled snaps
      ansible.builtin.shell:
        cmd: "snap remove {{ item.0 }} --revision={{ item.1 }}"
      with_items: "{{ snap_list_output.stdout_lines }}"
      when: "'disabled' in item"
      changed_when: false

    - name: Vacuum journalctl logs to limit size to 20M
      ansible.builtin.shell:
        cmd: "journalctl --vacuum-size=20M"
      changed_when: false

    - name: Perform apt update to check for updates
      ansible.builtin.shell:
        cmd: "apt update"
      changed_when: false

    - name: Check kernel version before patching
      ansible.builtin.command:
        cmd: "uname -r"
      register: kernel_version_before
      changed_when: false

    - name: Check for package upgrades without performing them
      ansible.builtin.shell:
        cmd: "apt-get --simulate dist-upgrade"
      register: apt_upgrade_simulate
      changed_when: false

    - name: Prompt for service restart confirmation if upgrades are detected
      ansible.builtin.pause:
        prompt: "Some packages need to be upgraded. Proceed with package upgrades and restart services if necessary? (yes/no)"
      register: upgrade_confirm
      when: apt_upgrade_simulate.stdout_lines | length > 0

    - name: Perform apt-get dist-upgrade if confirmed
      ansible.builtin.shell:
        cmd: "apt-get dist-upgrade -y"
      register: apt_upgrade_result
      changed_when: "'0 upgraded, 0 newly installed' not in apt_upgrade_result.stdout"
      when: upgrade_confirm.user_input | lower == 'yes'

    - name: Check kernel version after patching
      ansible.builtin.command:
        cmd: "uname -r"
      register: kernel_version_after
      changed_when: false

    - name: Restart services if packages were upgraded and confirmed
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ apt_upgrade_result | default({'packages': []}).packages }}"
      when: apt_upgrade_result.changed and upgrade_confirm.user_input | lower == 'yes'

    - name: Reboot if kernel version has changed
      ansible.builtin.reboot:
      when: kernel_version_before.stdout != kernel_version_after.stdout
      async: 0
      poll: 0
      ignore_errors: true
      changed_when: true

    - name: Display OS version changes
      ansible.builtin.debug:
        msg: |
          OS version changes:
            - Before patching: {{ kernel_version_before.stdout }}
            - After patching : {{ kernel_version_after.stdout }}
