---
- name: Linux OS Update v2

  hosts: "{{ target_hosts | default('localhost') | split(';') | select('match', '.+') | join(':') }}"

  become: true
  gather_facts: true

  vars:

    ansible_remote_tmp: "/tmp/ansible_tmp"

    # Jenkins checks out the Git repository into the workspace.
    # playbook_dir is:
    #
    #   <workspace>/ansible-roles/linux
    #
    # Therefore ../../reports is:
    #
    #   <workspace>/reports
    #
    os_update_report_directory: "{{ playbook_dir }}/../../reports"

  roles:
    - role: "{{ playbook_dir }}/os_update"
